# Generated by Django 3.2.9 on 2021-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('description', models.TextField(verbose_name='Short description lesson')),
                ('about', models.TextField(verbose_name='Everything about lesson')),
                ('photo', models.ImageField(upload_to='lesson', verbose_name='Photo lesson')),
            ],
        ),
    ]
