# Generated by Django 3.2.9 on 2021-11-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Manufacture's name")),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(upload_to='car', verbose_name='Picture')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='Published', max_length=10, verbose_name='status')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Car's name")),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=9, verbose_name='Phone number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red'), ('yellow', 'Yellow'), ('silver', 'Silver')], max_length=6, verbose_name='Color')),
                ('photo', models.ImageField(upload_to='car', verbose_name='Picture')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.manufacture')),
            ],
        ),
    ]
